VIDEOS = {
    # English
    1: [
        'https://www.youtube.com/watch?v=5jWVBjAEqjI',
        'https://www.youtube.com/watch?v=_Ym0LW_uPPk',
        'https://www.youtube.com/watch?v=wuxEpasO1po',
        'https://www.youtube.com/watch?v=MWzJl56tlEA',
        'https://www.youtube.com/watch?v=uVu4Me_n91Y',
        'https://www.youtube.com/watch?v=vm0UNn7tJ5o',
        'https://www.youtube.com/watch?v=4NzA1bLO3oQ',
        'https://www.youtube.com/watch?v=S67W0mVdukM',
        'https://www.youtube.com/watch?v=dykgtGv8ozs',
        'https://www.youtube.com/watch?v=hEm5NC_8cT0',
        'https://www.youtube.com/watch?v=THUtNNGnt5o',
        'https://www.youtube.com/watch?v=KYyOai2R7q8',
        'https://www.youtube.com/watch?v=AbQkZ_RxsiQ',
        'https://www.youtube.com/watch?v=GBSiB3i2Y9g',
        'https://www.youtube.com/watch?v=jJ25U6kEyQk',
        'https://www.youtube.com/watch?v=CA9I1UzQmjw',
    ],
    # Non-English
    0: [
        'https://www.youtube.com/watch?v=MmdOMkqGHTg',
        'https://www.youtube.com/watch?v=b9Dc2FkmJV0',
        'https://www.youtube.com/watch?v=RRU2Ppm112M',
        'https://www.youtube.com/watch?v=2jn53sOXwtc',
        'https://www.youtube.com/watch?v=UbkqE4fpvdI',
        'https://www.youtube.com/watch?v=zYR41nJ3n2c',
        'https://www.youtube.com/watch?v=Dzdg-0vldW4',
        'https://www.youtube.com/watch?v=ljGMhDSSGFU',
        'https://www.youtube.com/watch?v=9LnwBJP8xkA',
        'https://www.youtube.com/watch?v=KoTnb_0rH8k',
        'https://www.youtube.com/watch?v=TzUPVXPMzwI',
        'https://www.youtube.com/watch?v=kFYIllKTYLo',
        'https://www.youtube.com/watch?v=TOg4TZH9uS4',
        'https://www.youtube.com/watch?v=ck9bROhxrDI',
        'https://www.youtube.com/watch?v=p5Vdy7yLMEo',
        'https://www.youtube.com/watch?v=NVUiz_u2Jw0',
        'https://www.youtube.com/watch?v=OUeaTxXxHzE',
        'https://www.youtube.com/watch?v=T44NZgYILls',
        'https://www.youtube.com/watch?v=QfXc_OMDshU',
        'https://www.youtube.com/watch?v=JkyS0j652lI',
    ]
}
